function pic=ShowRobot(RobotStates)
    D=20;
    
    PatchX=[...
        RobotStates.X+cos(RobotStates.Theta*pi/180)*(RobotStates.Length/2)+sin(RobotStates.Theta*pi/180)*RobotStates.Width/2,...
        RobotStates.X+cos(RobotStates.Theta*pi/180)*(RobotStates.Length/2)-sin(RobotStates.Theta*pi/180)*RobotStates.Width/2,...
        RobotStates.X-cos(RobotStates.Theta*pi/180)*(RobotStates.Length/2)-sin(RobotStates.Theta*pi/180)*RobotStates.Width/2,...
        RobotStates.X-cos(RobotStates.Theta*pi/180)*(RobotStates.Length/2)+sin(RobotStates.Theta*pi/180)*RobotStates.Width/2];
    
    PatchY=[...
        RobotStates.Y+sin(RobotStates.Theta*pi/180)*(RobotStates.Length/2)-cos(RobotStates.Theta*pi/180)*(RobotStates.Width/2),...
        RobotStates.Y+sin(RobotStates.Theta*pi/180)*(RobotStates.Length/2)+cos(RobotStates.Theta*pi/180)*(RobotStates.Width/2),...
        RobotStates.Y-sin(RobotStates.Theta*pi/180)*(RobotStates.Length/2)+cos(RobotStates.Theta*pi/180)*(RobotStates.Width/2),...
        RobotStates.Y-sin(RobotStates.Theta*pi/180)*(RobotStates.Length/2)-cos(RobotStates.Theta*pi/180)*(RobotStates.Width/2)];
    
    
    
    
    
    patch(PatchX,PatchY,'k','EdgeColor','w');
    RobotStates.X=RobotStates.X+cos(RobotStates.Theta*pi/180)*RobotStates.LidarOffCenter;
    RobotStates.Y=RobotStates.Y+sin(RobotStates.Theta*pi/180)*RobotStates.LidarOffCenter;
    pic=rectangle('Position',[RobotStates.X-D/2,RobotStates.Y-D/2,D,D],...
          'Curvature',[1,1],...
         'LineWidth',1.5,'edgecolor','r')+line([RobotStates.X,RobotStates.X+D*cos(RobotStates.Theta*pi/180)/2],[RobotStates.Y,RobotStates.Y+D*sin(RobotStates.Theta*pi/180)/2],'Color','r','LineWidth',3);
    daspect([1,1,1]);


end